### PR TITLE
Create sqlite3 DB and migrations (#1)

### PR DESCRIPTION
**Pull request by sofakingworld**

### CODE REVIEW

**Comment by sofakingworld** [comment]
@pavkosykh come on, check this)

**Comment by pavkosykh** [comment]
I don't like your realisation. And i have several points why i think so:
1) you write to much code to maintain database status in actual state
2) i think bad idea before every start application  tru to run migrations. 


I tell you about this migration tool, please read the note:

https://medium.com/geekculture/db-migration-in-go-lang-d325effc55de

**Comment by sofakingworld** [comment]
> * you write to much code to maintain database status in actual state

I don't get about what status do you tell?

**Comment by sofakingworld** [comment]
i think bad idea before every start application tru to run migrations.


> 2\. i think bad idea before every start application  tru to run migrations.

It's great design, you do not need launch migrations separate of app start

article at medium is good for backend service, but for CLI application migrations should be at background for user

**Comment by pavkosykh** [comment]
okey. i understand your points. 
and think you are right. but i don't like your realization. 
i will write same functions designed by clean architecture and we can discuss it

**Pull request closed without merging**
